- name: Set OSX Defaults
  osx_defaults: >
    array_add={{ item.array_add|default('no') }}
    domain={{ item.domain }}
    key={{ item.key }}
    type={{ item.type }}
    value={{ item.value }}
    state={{ item.state|default('present') }}
  with_items: "{{ osx_settings }}"
